# Generated by Django 5.1 on 2024-09-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
    ]
